version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaskapp
    container_name: stock-data-visualizer
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1